/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Frankfurter API
 * Frankfurter is an open-source API for current and historical foreign exchange rates published by central banks.
 * OpenAPI spec version: 2.1.1
 */
import * as zod from 'zod'

/**
 * Returns exchange rates blended across providers. Without date params, returns the latest rates. Each record is a single currency pair.
 * @summary Get exchange rates
 */
export const getRatesQueryBaseDefault = `EUR`

export const GetRatesQueryParams = zod.object({
  date: zod.iso
    .date()
    .optional()
    .describe('Specific date (YYYY-MM-DD). Cannot be combined with from/to.'),
  from: zod.iso.date().optional().describe('Start of date range (YYYY-MM-DD)'),
  to: zod.iso.date().optional().describe('End of date range (YYYY-MM-DD). Defaults to today.'),
  base: zod.string().default(getRatesQueryBaseDefault).describe('Base currency (default: EUR)'),
  quotes: zod.string().optional().describe('Comma-separated list of quote currencies to include'),
  providers: zod.string().optional().describe('Comma-separated list of data providers to include'),
  group: zod
    .enum(['week', 'month'])
    .optional()
    .describe('Downsample rates by time period. Only applies to date ranges.'),
  expand: zod
    .enum(['providers'])
    .optional()
    .describe(
      "Comma-separated list of optional fields to include per record. Currently supports `providers`, which adds an array of `{ key, rate }` objects per record showing each provider's individual rate. Outliers excluded from the blend (and providers whose rate was overridden by a currency peg) are flagged with `excluded: true`. The field is omitted on synthesized peg rows where no provider published the quote. In CSV output, the `providers` column is encoded as `KEY:RATE` pairs joined by `|`, with a trailing `*` on excluded entries (e.g. `ECB:0.92|FED:1.50*`).",
    ),
})

export const getRatesResponseRateExclusiveMin = 0

export const getRatesResponseProvidersItemRateExclusiveMin = 0

export const GetRatesResponseItem = zod.object({
  date: zod.iso.date().describe('The date of the rate'),
  base: zod.string().describe('Base currency code'),
  quote: zod.string().describe('Quote currency code'),
  rate: zod.number().gt(getRatesResponseRateExclusiveMin).describe('Exchange rate value'),
  providers: zod
    .array(
      zod.object({
        key: zod.string().describe('Provider key'),
        rate: zod
          .number()
          .gt(getRatesResponseProvidersItemRateExclusiveMin)
          .describe("Provider's rate, rebased to the row's base"),
        excluded: zod
          .boolean()
          .optional()
          .describe('Present and true when this entry did not contribute to the blended rate'),
      }),
    )
    .optional()
    .describe(
      "Per-provider rates for this pair. Present only when `expand=providers` is set. Each entry has the provider's published rate (rebased to the row's base). Entries with `excluded: true` did not contribute to the blended `rate` — either flagged as outliers by the consensus filter, or overridden by a currency peg. Omitted on synthesized peg rows where no provider published the quote.",
    ),
})
export const GetRatesResponse = zod.array(GetRatesResponseItem)

/**
 * Returns the blended exchange rate for a single currency pair. Without a date param, returns the latest rate.
 * @summary Get a single exchange rate pair
 */
export const GetRateParams = zod.object({
  base: zod.string(),
  quote: zod.string(),
})

export const GetRateQueryParams = zod.object({
  date: zod.iso
    .date()
    .optional()
    .describe('Specific date (YYYY-MM-DD). Cannot be combined with from/to.'),
  providers: zod.string().optional().describe('Comma-separated list of data providers to include'),
})

export const getRateResponseRateExclusiveMin = 0

export const getRateResponseProvidersItemRateExclusiveMin = 0

export const GetRateResponse = zod.object({
  date: zod.iso.date().describe('The date of the rate'),
  base: zod.string().describe('Base currency code'),
  quote: zod.string().describe('Quote currency code'),
  rate: zod.number().gt(getRateResponseRateExclusiveMin).describe('Exchange rate value'),
  providers: zod
    .array(
      zod.object({
        key: zod.string().describe('Provider key'),
        rate: zod
          .number()
          .gt(getRateResponseProvidersItemRateExclusiveMin)
          .describe("Provider's rate, rebased to the row's base"),
        excluded: zod
          .boolean()
          .optional()
          .describe('Present and true when this entry did not contribute to the blended rate'),
      }),
    )
    .optional()
    .describe(
      "Per-provider rates for this pair. Present only when `expand=providers` is set. Each entry has the provider's published rate (rebased to the row's base). Entries with `excluded: true` did not contribute to the blended `rate` — either flagged as outliers by the consensus filter, or overridden by a currency peg. Omitted on synthesized peg rows where no provider published the quote.",
    ),
})

/**
 * Returns details for a single currency, including provider information or peg metadata.
 * @summary Get a single currency
 */
export const GetCurrencyParams = zod.object({
  code: zod.string(),
})

export const GetCurrencyResponse = zod.object({
  iso_code: zod.string().describe('ISO 4217 currency code'),
  iso_numeric: zod.string().nullish().describe('ISO 4217 numeric code'),
  name: zod.string().describe('Full currency name'),
  symbol: zod.string().nullish().describe('Currency symbol'),
  providers: zod
    .array(zod.string())
    .optional()
    .describe('Provider keys that publish this currency'),
  peg: zod
    .object({
      base: zod.string().optional(),
      rate: zod.number().optional(),
      authority: zod.string().optional(),
      source: zod.url().optional(),
    })
    .optional()
    .describe('Peg metadata, present only for pegged currencies'),
})

/**
 * Returns available currencies with their names and date ranges. By default, only active currencies are included.
 * @summary Get available currencies
 */
export const GetCurrenciesQueryParams = zod.object({
  scope: zod.enum(['all']).optional().describe("Set to 'all' to include legacy currencies"),
  providers: zod.string().optional().describe('Comma-separated list of data providers to include'),
})

export const GetCurrenciesResponseItem = zod.object({
  iso_code: zod.string().describe('ISO 4217 currency code'),
  iso_numeric: zod.string().nullish().describe('ISO 4217 numeric code'),
  name: zod.string().describe('Full currency name'),
  symbol: zod.string().nullish().describe('Currency symbol'),
  start_date: zod.iso.date().nullish().describe('Earliest available date'),
  end_date: zod.iso.date().nullish().describe('Latest available date'),
})
export const GetCurrenciesResponse = zod.array(GetCurrenciesResponseItem)

/**
 * Returns available exchange rate data providers with their base currency.
 * @summary Get available data providers
 */
export const getProvidersResponsePublishesMissedMin = 0

export const GetProvidersResponseItem = zod.object({
  key: zod.string().describe('Provider identifier'),
  name: zod.string().describe('Full provider name'),
  country_code: zod.string().nullish().describe('ISO 3166-1 alpha-2 country code'),
  rate_type: zod.string().nullish().describe('Official rate type as used by the source'),
  pivot_currency: zod.string().nullish().describe('Base currency for published rates'),
  data_url: zod.url().nullish().describe('Link to the data source'),
  terms_url: zod.url().nullish().describe('Link to terms of use'),
  start_date: zod.iso.date().nullish().describe('Earliest available date'),
  end_date: zod.iso.date().nullish().describe('Latest available date'),
  publish_cadence: zod
    .union([zod.literal('daily'), zod.literal('weekly'), zod.literal('monthly'), zod.literal(null)])
    .nullish()
    .describe(
      'How often the provider publishes rates. Determines the unit of publishes_missed: a count of days, ISO weeks, or calendar months. Null for historical-only providers with no scheduled cadence.',
    ),
  publishes_missed: zod
    .number()
    .min(getProvidersResponsePublishesMissedMin)
    .nullish()
    .describe(
      'Number of expected publishes missed since end_date, in units of publish_cadence. For daily providers, counts scheduled publish days strictly between end_date and today. For weekly and monthly providers, counts ISO weeks or calendar months between the latest imported bucket and the bucket whose publish window has already started. Null when the provider has no scheduled cadence or no imported data.',
    ),
  currencies: zod.array(zod.string()).describe('Currency codes covered by this provider'),
})
export const GetProvidersResponse = zod.array(GetProvidersResponseItem)
